### ISSUE TITLE
GiftCard Code Review

### ISSUE THREAD

**Issue by cbaron** [cbaron/Hazy#23]
Hey Scott,

Noticed the following in v/GiftCards

```
submit() {
              if( !this.validate( this.getFormValues() ) ) return Promise.resolve( this.onSubmitEnd() )
    
              const isPost = !Boolean( this.model.data[ this.key ]  )
    
              return ( isPost ? this.model.post() : this.model.put( this.model.data[ this.key ], this.omit( this.model.data, [ this.key ] ) ) )
              .then( () => this.Toast.createMessage( 'success', this.toastSuccess || `Success` ) )
              .then( () => {
                  this.emit( isPost ? 'posted' : 'put', Object.assign( {}, this.model.data ) )
                  this.model.data = { }
                  this.clear()
                  this.onSubmitEnd()
              } )
          }
```

Why did you do that^

**Comment by ScottAP108** [comment]
We discussed it briefly. When a gift card transaction goes through, I navigate back to the home page in response to the 'posted' event. I thought it looked and felt bad to navigate immediately to home while Toast is displaying (which is what happens with the standard `submit` function), so this is just a heavy-handed override to have Toast finish before the user is sent back to home. I'm sure there's a more elegant way to do it.

**Comment by cbaron** [comment]
Alright, I will think on it.
